[program:attendance-high-priority-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --queue=attendance-high-priority --sleep=3 --tries=3 --timeout=30 --max-jobs=1000 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue-high-priority.log
stopwaitsecs=3600
