[program:reporting-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --queue=reporting --sleep=3 --tries=1 --timeout=300 --max-jobs=100 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue-reporting.log
stopwaitsecs=3600
